### ISSUE TITLE
[bug] get_neighbors() may fail with "Interrupted system call"

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwrt-openwisp-monitoring#15]
```
lua: /usr/sbin/netjson-monitoring:67: Interrupted system call
stack traceback:
	[C]: in function '(for generator)'
	/usr/sbin/netjson-monitoring:67: in function 'get_ip_neigh'
	/usr/sbin/netjson-monitoring:84: in function 'get_neighbors'
	/usr/sbin/netjson-monitoring:181: in main chunk
	[C]: ?
```

I need to test this on more devices before ruling out if it's a system issue or something that has to be dealt with in the code.

**Comment by devkapilbansal** [comment]
Found this error cause mentioned here too:-
https://github.com/openresty/lua-nginx-module/issues/1346#issuecomment-401151157

**Comment by devkapilbansal** [comment]
After investigating further I found that this occurs when process `io.popen()` is not finished due to large ouput and an operation is performed on it. Like mentioned in the comment above, `SIGCHLD interrupts EINTR` signal. 

get_neighbors() works fine if system call is not started till now, i.e. output returned by `io.popen('ip neigh')` is nil or the call is finished.

What we may do is catch if this error occurs and retry running the output after waiting for a second or two, or may catch these signals.

P.S.:- This error is specific to how `popen` works instead of get_neighbors(). However I am not sure, so please take it with a pinch of salt. :sweat_smile:
