### ISSUE TITLE
Avoid hard dependencies, document dependencies

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwrt-openwisp-monitoring#18]
Current dependencies:

- lua-cjson
- rpcd-mod-iwinfo

We may replace cjson with some other library already available on OpenWRT ([asked for a suggestion in the OpenWRT forum](https://forum.openwrt.org/t/lua-json-library-available-by-default/72198)).

Make sure that if the package `rpcd-mod-iwinfo` is not installed, these two lines won't fail:
https://github.com/openwisp/lua-monitoring/blob/master/netjson-monitoring.lua#L398-L399
Ideally we should check for the presence of the feature before the loop, and skip the loop if the feature is not available.

We should add a brief README which should tell users to install package X.

**Comment by nepython** [comment]
@nemesisdesign, I think the package [luci-lib-json](https://openwrt.org/packages/pkgdata/luci-lib-json) can be used as a replacement for cjson. I did an exhaustive search to find this listed on the [lua-users site](http://lua-users.org/wiki/JsonModules) which also contains a list of many other lua implementations but none seem to be built-in. I tested this package with a simple script as below and it worked fine.
```lua
json = require('luci.json')


-- Lua table to JSON object
test = {
  one='first',two='second',three={2,3,5}
}

jsonTest = json.encode(test)

print('JSON encoded test is: ' .. jsonTest)

-- JSON object to Lua table
result = json.decode(jsonTest)

print ("The decoded table result:")
table.foreach(result,print)
print ("The decoded table result.three")
table.foreach(result.three, print)
```
:warning: This package was supposed to be built-in but this wasn't the case for me and I had to install it on my VM. Please confirm if this is also the case on an actual openwrt device or they have this package built-in, which I think should be the case (because almost all other luci packages are installed in my VM).

**Comment by nemesisdesign** [comment]
So we would be switching one dependency for another, maybe luci-lib-json is smaller, but I have to assess. Probably we can put this in standby.

**Comment by nemesisdesign** [comment]
We can close this now! :+1:
